# Version 2.0.0
# To install the git pre-commit hooks run:
#   pre-commit install --install-hooks
# To update the versions:
#   pre-commit autoupdate
repos:
  # General Pre-Commit Hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-toml
  # Using Black as the formatter
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3.10
      - id: black-jupyter
        language_version: python3.10
    # Using Ruff as the linter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.282
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
        types_or: [python, jupyter]
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.6.0
    hooks:
      - id: commitizen