name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Pull Docker image
      run: docker pull klangkk/stock-analysis:latest
    - name: Run Docker image
      uses: addnab/docker-run-action@v3
      with:
        image: 'klangkk/stock-analysis:latest'
        run: |
          kedro run
