name: Kedro pipeline

on:
  schedule:
    - cron: '55 6 * * *' # This line sets the action to run every day at 14:40 Singapore time (UTC+8)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.5' # replace '3.x' with your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd src
        pip install -r requirements.txt

    - name: Run Kedro
      run: kedro run
